### PR TITLE
build: update build plugin to 5.2.3

### PR DESCRIPTION
**Pull request by sdelamo**
rename root project name to -parent

### CODE REVIEW

**Comment by sdelamo** [comment]
@timyates can you work on this?

**Comment by timyates** [comment]
@melix Does something else need updating when we move to `io.micronaut.build.shared.settings`:`5.2.3`?

It's failing here https://github.com/micronaut-projects/micronaut-build/blob/a88b478a439bac4754e3641b69b389909ab994e6/src/main/groovy/io/micronaut/build/MicronautBomPlugin.java#L363 with a NoSuchMethodError 🤔

**Comment by melix** [comment]
You need to upgrade to Gradle 7.4.1. Not sure why this project isn't up-to-date.

**Comment by timyates** [comment]
> You need to upgrade to Gradle 7.4.1. Not sure why this project isn't up-to-date.

Awesome, thanks 😀

**Comment by timyates** [comment]
I wonder if it's because this PR didn't get merged

https://github.com/micronaut-projects/micronaut-kotlin/pull/355

Anyway @sdelamo, this is ready to go I can't add you as a reviewer as you raised it 😔

**Pull request merged**
