### PR TITLE
WIP: Idiomatic kotlin bootstrap

### LINKED ISSUE #44: Idiomatic kotlin bootstrap
I just want to ask, if it can be possible to add some kotlin specific top level bootstrap method for micronaut, for example something like this:

```kotlin
inline fun <reified T : Any> startApplication(vararg args: String, initializer: Micronaut.() -> Unit = {}) {
    Micronaut.build(*args)
        .mainClass(T::class.java)
        .apply(initializer)
        .start()
}

inline fun <reified T : Throwable> Micronaut.mapError(noinline mapper: (T) -> Int): Micronaut {
    return this.mapError(T::class.java, mapper)
}
```

It will simplify micronaut usage for kotlin developers and make it feel more like kotlin specific. The usage then can be like this:

```kotlin
object Application {
    fun main(args: Array<String>) {
        startApplication<Application>(*args) {
            packages("org.example.app")
            mapError<RuntimeException> { 500 }
        }
    }
}
```

I would like to create a PR, but i dont know where to start. I you agree with this addition, can you please point me to the right direction? If not, just close it :)

### PR DESCRIPTION
**Pull request by morki**
Usage:

```kotlin
fun main(args: Array<String>) {
    startApplication<Application>(*args) {
        packages("org.example.app")
        mapError<RuntimeException> { 500 }
    }
}
```

Fixes #44

### CODE REVIEW

**Comment by graemerocher** [comment]
Thanks, we will need documentation, tests and to resolve the compilation errors :)

**Comment by morki** [comment]
@graemerocher Of course, can you please point me to where documentation can be placed within this PR?

**Comment by morki** [comment]
@graemerocher documentation and compilation errors resolved, but i have no idea how to create tests for this extension behaviour. Can you please help point me to the right direction? Thank you :)

**Comment by graemerocher** [comment]
You can see tests that start the application context in the regular way here https://github.com/micronaut-projects/micronaut-kotlin/blob/master/kotlin-runtime/src/test/kotlin/io/micronaut/jackson/kotlin/KotlinModuleFactoryTest.kt

I imagine another set of similar tests that use the `startApplication` function would suffice

**Comment by willbuck** [comment]
@morki if you get stuck or have questions I'm happy to provide further assistance :)

**Comment by morki** [comment]
@willbuck Hi thank you, i got stuck with the tests, i can't think how it can be tested, because it is replacing builder pattern...

**Comment by willbuck** [comment]
@morki I understand a unit test being somewhat tricky to write if you're trying to capture a call to `Micronaut.build()`, but I think an integration test that asserts the application has started (as Graeme suggested) would work just fine (they are plenty fast for our purposes; hurray speedy Micronaut!).

Something like:

```
@Test
fun testStartApplication() {
    startApplication<Application>().use {
        assertTrue(it.containsBean(ObjectMapper::class.java)) // Or some other bean that should be there once the application has started
    }
}
```

On a side note, I will be opening a PR for issue #49 that puts these extension functions in a separate module (in case someone would want to omit them), but I will take care of migrating this over.

Let me know if you need any further assistance!

**Comment by willbuck** [comment]
Hey @morki ! I ended up moving the code over into the PR that will add the `kotlin-extension-functions` module, take a look and tell me what you think! https://github.com/micronaut-projects/micronaut-kotlin/pull/53

**Comment by morki** [comment]
Closing as implemented in #53 by @willbuck.

**Pull request closed without merging**
